### ISSUE TITLE
C++: "#define PROJ_PERSISTENCE true" exists twice in the template

### ISSUE THREAD

**Issue by haviital** [felipemanga/FemtoIDE#100]
When creating a new C++ project, "#define PROJ_PERSISTENCE true" exists twice in the my_settings.h

**Comment by haviital** [comment]
Also as persistence is defined in my_settings.h, it is probably better to leave out from the default main.cpp (`PD::persistence = true;`)

**Comment by felipemanga** [comment]
Thanks for the heads-up regarding the duplicate define.
As for the `PD::persistence = true`, it's necessary to have it in the cpp as well, since the default is false even with `#define PROJ_PERSISTENCE true`.
