### ISSUE TITLE
IDE: CPP project not supported by beautify.js

### ISSUE THREAD

**Issue by HomineLudens** [felipemanga/FemtoIDE#44]
Looking for alternatives: https://github.com/google/code-prettify
Seems to support both java, c, c++

**Comment by felipemanga** [comment]
code-prettify appears to be for creating syntax-highlighted HTML, not for reformatting code.
I haven't been able to find a beautifier that supports both Java and C++ while not dragging in a bunch of dependencies. :(
In the mean time, I altered beautify.js so it wouldn't split `0.0f` into `0.0 f`.

**Comment by felipemanga** [comment]
It appears `clangd` has support for tidying code. Replacing beautify.js with it for C/C++ files should be quick and simple.

**Comment by felipemanga** [comment]
I'm closing this for now, if any problems arise with the current implementation just open a new issue.
