### ISSUE TITLE
No module or line number in the error message: "TypeError: Cannot convert undefined or null to object" 

### ISSUE THREAD

**Issue by haviital** [felipemanga/FemtoIDE#52]

**Comment by haviital** [comment]
Here is the project which caused it
[ZombieFlock.zip](https://github.com/felipemanga/FemtoIDE/files/3500960/ZombieFlock.zip)

**Comment by felipemanga** [comment]
Thanks for the report. Since it's an internal compiler error, getting the location is impossible... but it shouldn't happen any more since #53 was fixed.
