### ISSUE TITLE
IDE: Cannot close the output window

### ISSUE THREAD

**Issue by haviital** [felipemanga/FemtoIDE#55]
The pixel editor do not fit in the window fully (e.g. half of the palette is not visible) as the output window takes space in the bottom.

![image](https://user-images.githubusercontent.com/1862346/63115732-80e9f680-bfa0-11e9-96de-43d1737c9702.png)

**Comment by felipemanga** [comment]
Just press esc?

**Comment by haviital** [comment]
yes, that works! Maybe there should be a tooltip or a close button to make it easier to find.

**Comment by felipemanga** [comment]
The output window is in need of a proper polish. I'll close this issue for now and once I've decided what to do with the UI in general, I'll open new issues. :+1:
