### ISSUE TITLE
IDE: Add a button to open project folder with OS file manager

### ISSUE THREAD

**Issue by HomineLudens** [felipemanga/FemtoIDE#65]
I'd love to have a way to open the project folder in OS file manager with a button o menu. 
That would simplify the access to project's file to modify with external programs.

**Comment by felipemanga** [comment]
Needs confirmation that it works on Windows and OSX.

**Comment by HomineLudens** [comment]
In win10 the command `#start .` from the Execute Command input box, open the project folder in the OS File Browser.
Actually neither the `explorer` command for any project folder, neither the `Open Externally` button in the entry context menu, works correctly.
The command just open a prompt command with the title bar pointing to the selected entry full path.

**Comment by HomineLudens** [comment]
Seems fixed by https://github.com/felipemanga/FemtoIDE/commit/ff99915279995c0bf709061d6f1d9b456aaa77cb on windows
