### ISSUE TITLE
FemtoLib:  error in LowRes mode getPixel

### ISSUE THREAD

**Issue by bl-ackrain** [felipemanga/FemtoIDE#72]
https://github.com/felipemanga/FemtoIDE/blob/10d1fcabc555422141cb5662e2f3cff1a874fb0c/javacompiler/femto/mode/LowRes16Color.java#L32

getPixel should return pixel value not void

**Comment by felipemanga** [comment]
:man_facepalming: 
Thanks for the heads up, I haven't been paying much attention to LowRes mode recently.
