### ISSUE TITLE
C++: Building with an unsaved file will use the previous version of this file

### ISSUE THREAD

**Issue by carbonacat** [felipemanga/FemtoIDE#79]
1. Open a C++ project.
2. Edit a C++ file that is used by the build process.
3. Do not save it.
4. Build by pressing either `Ctrl+Enter`, `Ctrl+G`, `Ctrl+B`.

Results: The file is saved, but its previous content are used by the build process.
Expected: The file is saved and its new content are used by the build process.

**Comment by felipemanga** [comment]
Fixed
