### ISSUE TITLE
C++ Project files not compiling on windows 10 64bit

### ISSUE THREAD

**Issue by Dreamer2345** [felipemanga/FemtoIDE#97]
`c:/users/new/desktop/ide-windows-v0.1.7/windows/arm/bin/../lib/gcc/arm-none-eabi/8.2.1/../../../../arm-none-eabi/bin/ld.exe
: 149.o: in function `Pokitto::Sound::volumeUp()':
PokittoSound.cpp:(.text._ZN7Pokitto5Sound8volumeUpEv+0x22): undefined reference to `Pokitto::setHWvolume(unsigned char)'
c:/users/new/desktop/ide-windows-v0.1.7/windows/arm/bin/../lib/gcc/arm-none-eabi/8.2.1/../../../../arm-none-eabi/bin/ld.exe: 149.o: in function `Pokitto::Sound::volumeDown
()':
PokittoSound.cpp:(.text._ZN7Pokitto5Sound10volumeDownEv+0x1e): undefined reference to `Pokitto::setHWvolume(unsigned char)'
c:/users/new/desktop/ide-windows
-v0.1.7/windows/arm/bin/../lib/gcc/arm-none-eabi/8.2.1/../../../../arm-none-eabi/bin/ld.exe: 149.o: in
 function `Pokitto::Sound::setMaxVol(short)':
PokittoSound.cpp:(.text._ZN7Pokitto5Sound9setMaxVolEs+0x34): undefined reference to `Pokitto::setHWvolume(unsigned char)'
c
:/users/new/desktop/ide-windows-v0.1.7/windows/arm/bin/../lib/gcc/arm-none
-eabi/8.2.1/../../../../arm-none-eabi/bin/ld.exe: 149.o: in function `Pokitto
::Sound::setVolume(short)':
PokittoSound.cpp:(.text._ZN7Pokitto5Sound9setVolumeEs+0x1c): undefined reference to `Pokitto::setHWvolume(unsigned
 char
)'
collect2.exe: error: ld returned 1 exit status`

Ive just downloaded the IDE and gone to create and compile the example project however this occured when compiling

**Comment by felipemanga** [comment]
Seems this issue has been resolved. I'll close it, but feel free to open another one if you have any problems.
